name: Publish-AadAuthenticationFactory
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "publishToGallery"
  publishToGallery:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
        
    - name: Build Module
      shell: pwsh
      run: |
        "Copying license file"
        Copy-Item -Path "$env:GITHUB_WORKSPACE\LICENSE" -Destination "$env:GITHUB_WORKSPACE\Module\AadAuthenticationFactory\LICENSE.txt" -Force
        "Building module"
        &"$env:GITHUB_WORKSPACE\Workflow\BuildModule.ps1" -RootPath "$env:GITHUB_WORKSPACE"
        "Setting up packages"
        &"$env:GITHUB_WORKSPACE\Workflow\SetupPackages.ps1" -RootPath "$env:GITHUB_WORKSPACE" -NugetPath $env:nuget


    - name: Install AzureSignTool
      shell: pwsh
      run: |
        dotnet tool install --global AzureSignTool
      
  
    - name: Sign files
      shell: pwsh
      env: 
        CODESIGNING_KEYVAULTURI: ${{ github.CODESIGNING_KEYVAULTURI }}
        TENANTINTEGRATION_CLIENTID: ${{ github.TENANTINTEGRATION_CLIENTID }}
        TENANTINTEGRATION_TENANTID: ${{ github.TENANTINTEGRATION_TENANTID }}
        CODESIGNING_CERTNAME: ${{ github.CODESIGNING_CERTNAME }}
        
      run: |
        $files = Get-ChildItem "$env:GITHUB_WORKSPACE\Module\AadAuthenticationFactory" -File -Recurse -Include *.ps1, *.ps1xml, *.psd1, *.psm1, *.pssc, *.psrc, *.cdxml
        Write-Host "url:" ${{ vars.CODESIGNING_KEYVAULTURI }}
        Write-Host "clientId:" $env:TENANTINTEGRATION_CLIENTID
        Write-Host "tenant:" $env:TENANTINTEGRATION_TENANTID
        Write-Host "secret:" ${{ secrets.TENANTINTEGRATION_CLIENTSECRET }}
        Write-Host "certName:" $env:CODESIGNING_CERTNAME
        try {
            foreach ($file in $files) {
                azuresigntool sign -kvu $env:CODESIGNING_KEYVAULTURI -kvi $env:TENANTINTEGRATION_CLIENTID -kvt $env:TENANTINTEGRATION_TENANTID -kvs ${{ secrets.TENANTINTEGRATION_CLIENTSECRET }} -kvc $env:CODESIGNING_CERTNAME -v "$($file.FullName)" 
            }
        }
        catch {
            Write-Host "Error: $($_.Exception)"
            throw
        }
        Write-Host "Signed files summary:"
        Get-AuthenticodeSignature -FilePath $files
        

    - name: Publish
      #Publish to PS Gallery
      shell: pwsh
      if: ${{ github.event_name != 'workflow_dispatch' }}
      env:
        SECRET: ${{ secrets.PSGallery_APIKey }}
      run: |
        write-host "Publishing from: $env:GITHUB_WORKSPACE\Module\AadAuthenticationFactory"
        try
        {
          $env:PSModulePath = "$env:PSModulePath;$env:GITHUB_WORKSPACE\Module"
          "PSModulePath: $env:PSModulePath"
          Publish-Module -Path "$env:GITHUB_WORKSPACE\Module\AadAuthenticationFactory" -NuGetApiKey "$env:SECRET"
        }
        catch
        {
          Write-Host "Error: $($_.Exception)"
          throw
        }

    - name: Create Release
      #Create a release
      id: create_release
      if: ${{ github.event_name != 'workflow_dispatch' }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        draft: false
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        name: Release ${{ github.ref }}   
